<a href="https://colab.research.google.com/github/Malav786/PyTorch_Tutor/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor_a = torch.rand(7, 7)
tensor_a

tensor([[0.3556, 0.1681, 0.6074, 0.6264, 0.4113, 0.2012, 0.4508],
        [0.7418, 0.7099, 0.4485, 0.7905, 0.6787, 0.1017, 0.2245],
        [0.5581, 0.1874, 0.4825, 0.0134, 0.7692, 0.5738, 0.6531],
        [0.3823, 0.8013, 0.2569, 0.1937, 0.4003, 0.4009, 0.3276],
        [0.5667, 0.1580, 0.7931, 0.6562, 0.7577, 0.3335, 0.4118],
        [0.5554, 0.5712, 0.5519, 0.7034, 0.8067, 0.5056, 0.5565],
        [0.2564, 0.7656, 0.1120, 0.8248, 0.4022, 0.6322, 0.6747]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_b = torch.rand(1, 7)

# Perform matrix multiplication
tensor_a.matmul(tensor_b.T)

tensor([[1.3024],
        [1.8471],
        [1.7763],
        [1.4793],
        [1.8791],
        [2.1330],
        [1.6332]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
tensor_x = torch.rand(7, 7)
tensor_y = torch.rand(1, 7)

# Matrix multiply tensors
tensor_x.matmul(tensor_y.T)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)
tensor_a, tensor_b


Device: cuda


(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_a.matmul(tensor_b.T)


tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(tensor_a)

# Find min
min = torch.min(tensor_a)

max, min


(tensor(0.7262, device='cuda:0'), tensor(0.1123, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
argmax = torch.argmax(tensor_a)

# Find arg min
argmin = torch.argmin(tensor_a)

argmax, argmin


(tensor(4, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_a = torch.rand(1, 1, 1, 10)


# Remove single dimensions
tensor_b = tensor_a.squeeze()


# Print out tensors and their shapes
print(tensor_a, tensor_a.shape)
print(tensor_b, tensor_b.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
